<!DOCTYPE html><html lang=en><head><meta charset=utf-8><meta http-equiv=X-UA-Compatible content="IE=edge"><meta name=viewport content="width=device-width,initial-scale=1,maximum-scale=1,minimum-scale=1,user-scalable=no"><link rel="shortcut icon" href=/favicon.ico><title>4plbox</title><meta name=apple-mobile-web-app-capable content=yes><meta name=apple-mobile-web-app-status-bar-style content=default><meta name=apple-mobile-web-app-title content=Pragmatic><meta name=apple-touch-fullscreen content=yes><link rel=apple-touch-icon sizes=57x57 href=/static/icons/apple-icon-57x57.png><link rel=apple-touch-icon sizes=60x60 href=/static/icons/apple-icon-60x60.png><link rel=apple-touch-icon sizes=72x72 href=/static/icons/apple-icon-72x72.png><link rel=apple-touch-icon sizes=76x76 href=/static/icons/apple-icon-76x76.png><link rel=apple-touch-icon sizes=114x114 href=/static/icons/apple-icon-114x114.png><link rel=apple-touch-icon sizes=120x120 href=/static/icons/apple-icon-120x120.png><link rel=apple-touch-icon sizes=144x144 href=/static/icons/apple-icon-144x144.png><link rel=apple-touch-icon sizes=152x152 href=/static/icons/apple-icon-152x152.png><link rel=apple-touch-icon sizes=180x180 href=/static/icons/apple-icon-180x180.png><link rel=icon type=image/png sizes=192x192 href=/static/icons/android-icon-192x192.png><link rel=icon type=image/png sizes=32x32 href=/static/icons/favicon-32x32.png><link rel=icon type=image/png sizes=96x96 href=/static/icons/favicon-96x96.png><link rel=icon type=image/png sizes=16x16 href=/static/icons/favicon-16x16.png><link rel=manifest href=/manifest.json><meta name=msapplication-TileColor content=#ffffff><meta name=msapplication-TileImage content=/static/icons/ms-icon-144x144.png><meta name=theme-color content=#ffffff><meta name=description content="Element UI Vuejs design admin template with pre-built apps and pages"><meta name=keywords content="HTML,CSS,VueJs,JAVASCRIPT,JS,element,admin,dashboard,theme,html dashboard, html css dashboard, web dashboard,vue dashboard, premium vue.js dashboard, vue.js admin template"><meta name=author content=Linko><meta name=twitter:card content=summary_large_image><meta name=twitter:title content="Pragmatic - Vue.js Admin Template"><meta name=twitter:description content="Element UI Vuejs design admin template with pre-built apps and pages"><meta name=twitter:site content=@Linko_ddm><meta name=twitter:creator content=@Linko_ddm><meta name=og:title content="Pragmatic - Vue.js Admin Template"><meta name=og:description content="Element UI Vuejs design admin template with pre-built apps and pages"><meta name=og:site_name content=Pragmatic><meta name=og:type content=website><meta property=og:title content="Pragmatic - Vue.js Admin Template"><meta property=og:description content="Element UI Vuejs design admin template with pre-built apps and pages"><meta property=og:site_name content=Pragmatic><meta property=og:type content=website><style>.splash-screen {
			background: #4a596a;
			position: fixed;
			top: 0;
			left: 0;
			bottom: 0;
			right: 0;
			z-index: 99999;
		}
		.splash-screen > .wrap {
			position: absolute;
			top: 50%;
			left: 50%;
			transform: translateX(-50%) translateY(-50%);
		}
		.splash-screen > .wrap > img {
			margin: 30px auto;
			display: block;
			width: 100px;
		}
		.splash-screen > .wrap > img.logo{
			-webkit-filter: drop-shadow(0px 2px 2px rgba(0, 0, 0, 0.3));
			filter: drop-shadow(0px 2px 2px rgba(0, 0, 0, 0.3));
		}</style><link rel=preload as=script href=/js/vendor.e123a2fb.js><link rel=preload as=script href=/js/app.a15171fc.js><link rel=preload as=style href=/css/app.4107a07b.css><link rel=prefetch href=/js/0.afa87ad0.js><link href=/css/app.4107a07b.css rel=stylesheet></head><body class=theme-default><div id=app><div class=splash-screen><div class=wrap><img src=/Ripple-2s-200px.gif alt=loading-image></div></div></div><script type=text/javascript>(function(e){var n=window["webpackJsonp"];window["webpackJsonp"]=function(r,a,c){for(var i,u,f,l=0,s=[];l<r.length;l++)u=r[l],t[u]&&s.push(t[u][0]),t[u]=0;for(i in a)Object.prototype.hasOwnProperty.call(a,i)&&(e[i]=a[i]);n&&n(r,a,c);while(s.length)s.shift()();if(c)for(l=0;l<c.length;l++)f=o(o.s=c[l]);return f};var r={},t={3:0};function o(n){if(r[n])return r[n].exports;var t=r[n]={i:n,l:!1,exports:{}};return e[n].call(t.exports,t,t.exports,o),t.l=!0,t.exports}o.e=function(e){var n=t[e];if(0===n)return new Promise(function(e){e()});if(n)return n[2];var r=new Promise(function(r,o){n=t[e]=[r,o]});n[2]=r;var a=document.getElementsByTagName("head")[0],c=document.createElement("script");c.type="text/javascript",c.charset="utf-8",c.async=!0,c.timeout=12e4,o.nc&&c.setAttribute("nonce",o.nc),c.src=o.p+"js/"+e+"."+{0:"afa87ad0"}[e]+".js";var i=setTimeout(u,12e4);function u(){c.onerror=c.onload=null,clearTimeout(i);var n=t[e];0!==n&&(n&&n[1](new Error("Loading chunk "+e+" failed.")),t[e]=void 0)}return c.onerror=c.onload=u,a.appendChild(c),r},o.m=e,o.c=r,o.d=function(e,n,r){o.o(e,n)||Object.defineProperty(e,n,{configurable:!1,enumerable:!0,get:r})},o.n=function(e){var n=e&&e.__esModule?function(){return e["default"]}:function(){return e};return o.d(n,"a",n),n},o.o=function(e,n){return Object.prototype.hasOwnProperty.call(e,n)},o.p="/",o.oe=function(e){throw console.error(e),e}})([]);
//# sourceMappingURL=/js/manifest.d350e9db.js.map</script><script type=text/javascript src=/js/vendor.e123a2fb.js></script><script type=text/javascript src=/js/app.a15171fc.js></script></body></html>